// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdqpuuyhsdtiudqaderf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkcXB1dXloc2R0aXVkcWFkZXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NjE1MTYsImV4cCI6MjA4NzQzNzUxNn0.EAKfvh_lmDARt4TGENCnreMzt544_XBP6R004ZNWuSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});